// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/WrathForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/WrathForgedCore/blob/master/LICENSE> for full information.
using WrathForged.Serialization;

namespace WrathForged.Models
{
    /// <summary>
	/// SRP token based on Trinitycore/Mangos/WoW authentication protocol.
	/// Review http://srp.stanford.edu/design.html for more information
	/// </summary>
	[ForgedSerializable]
    public class SRPToken
    {
        /// <summary>
        /// Half of the ephemerial public key.
        /// </summary>
        [SerializableProperty(1, FixedCollectionSize = 32)]
        public byte[]? B { get; set; }

        /// <summary>
        /// A generator modulo N.
        /// (I don't really know what that means)
        /// </summary>
        [SerializableProperty(2, CollectionSizeLengthType = TypeCode.Byte)]
        public byte[]? G { get; set; }

        /// <summary>
        /// A large safe prime (N = 2q+1, where q is prime)
        /// </summary>
        [SerializableProperty(3, CollectionSizeLengthType = TypeCode.Byte)]
        public byte[]? N { get; set; }

        //SRP_6_S
        /// <summary>
        /// User salt (randomly generated by server. Used to make data ephemeral)
        /// </summary>
        [SerializableProperty(4, FixedCollectionSize = 32)]
        public byte[]? Salt { get; set; }
    }
}