DROP TABLE IF EXISTS `GMSurveyCurrentSurvey`; 
CREATE TABLE `GMSurveyCurrentSurvey` ( `ID` INT NOT NULL DEFAULT '0', `GMSURVEY_ID` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `GMSurveyCurrentSurvey` VALUES (0,9),
(1,9),
(2,9),
(3,9),
(4,9),
(5,9),
(6,9),
(7,9),
(8,9); 
