DROP TABLE IF EXISTS `GMSurveySurveys`; 
CREATE TABLE `GMSurveySurveys` ( `ID` INT NOT NULL DEFAULT '0', `Q_1` INT NOT NULL DEFAULT '0', `Q_2` INT NOT NULL DEFAULT '0', `Q_3` INT NOT NULL DEFAULT '0', `Q_4` INT NOT NULL DEFAULT '0', `Q_5` INT NOT NULL DEFAULT '0', `Q_6` INT NOT NULL DEFAULT '0', `Q_7` INT NOT NULL DEFAULT '0', `Q_8` INT NOT NULL DEFAULT '0', `Q_9` INT NOT NULL DEFAULT '0', `Q_10` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `GMSurveySurveys` VALUES (6,28,29,30,31,32,0,0,0,0,0),
(9,35,36,37,38,39,40,41,0,0,0); 
