DROP TABLE IF EXISTS `GMTicketCategory`; 
CREATE TABLE `GMTicketCategory` ( `ID` INT NOT NULL DEFAULT '0', `Category_Lang_enUS` TEXT NULL, `Category_Lang_enGB` TEXT NULL, `Category_Lang_koKR` TEXT NULL, `Category_Lang_frFR` TEXT NULL, `Category_Lang_deDE` TEXT NULL, `Category_Lang_enCN` TEXT NULL, `Category_Lang_zhCN` TEXT NULL, `Category_Lang_enTW` TEXT NULL, `Category_Lang_zhTW` TEXT NULL, `Category_Lang_esES` TEXT NULL, `Category_Lang_esMX` TEXT NULL, `Category_Lang_ruRU` TEXT NULL, `Category_Lang_ptPT` TEXT NULL, `Category_Lang_ptBR` TEXT NULL, `Category_Lang_itIT` TEXT NULL, `Category_Lang_Unk` TEXT NULL, `Category_Lang_Mask` INT UNSIGNED NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `GMTicketCategory` VALUES (0,"<not set>","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (1,"Stuck","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (2,"Behavior/Harassment","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (3,"Guild","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (4,"Item","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (5,"Environmental","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (6,"Non-Quest/Creep","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (7,"Quest/Quest NPC","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (8,"Technical","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (9,"Account/Billing","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (10,"Character","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (11,"Arena/Honor item issues","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (12,"Arena/Honor points issues","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (13,"Botting/Cheating/Hacking","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (14,"Bug report","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (15,"Compromised account issue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (16,"Game suggestions","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (17,"Gameplay question","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (18,"Guild bank issue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (19,"Guild master issue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (20,"Harassment","","","","","","","","","","","","","","","",16712191); 
INSERT INTO `GMTicketCategory` VALUES (21,"Inappropriate name Guild/Arena/Character/Pet","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (22,"Known issue fix","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (23,"Latency/Lag report","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (24,"Looting issue/mistake","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (25,"Mail issue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (26,"Non in game related inquiry","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (27,"Parental controls/CAIS","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (28,"PCNC","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (29,"PCT","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (30,"Restoration status/follow up","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (31,"Server/Instance issues","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (32,"Spam","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (33,"Suicide case","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (34,"Suspension questions","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (35,"Technical/Sound/Graphics issue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (36,"UI issue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `GMTicketCategory` VALUES (37,"Scam Report","","","","","","","","","","","","","","","",16712191); 
