DROP TABLE IF EXISTS `ObjectEffectGroup`; 
CREATE TABLE `ObjectEffectGroup` ( `ID` INT NOT NULL DEFAULT '0', `Name` TEXT NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `ObjectEffectGroup` VALUES (33,"vr_elevator_lift_always"),
(34,"vr_elevator_lift_accelerating"),
(157,"FlyingMachineMount_Sprint"),
(158,"WintergraspCatapult_Moving"),
(159,"WintergraspCatapult_NotMoving"),
(160,"FlyingMachineMount_Stand"),
(161,"FlyingMachineMount_Walk"),
(162,"FlyingMachineMount_ShuffleLeft"),
(163,"FlyingMachineMount_ShuffleRight"),
(164,"FlyingMachineMount_WalkBackwards"),
(165,"FlyingMachineMount_JumpStart"),
(166,"FlyingMachineMount_JumpEnd"),
(167,"FlyingMachineMount_SwimRight"),
(168,"FlyingMachineMount_SwimLeft"),
(169,"FlyingMachineMount_Swim"),
(170,"FlyingMachineMount_SwimBackwards"),
(171,"FlyingMachineMount_SwimIdle"),
(172,"FlyingMachineMount_JumpLandRun"),
(173,"FlyingMachineMount_Ascending"),
(175,"WintergraspCatapult_LoadThrown"),
(176,"WintergraspCatapult_AttackThrown"),
(181,"RocketMount_Stand"),
(182,"RocketMount_Walk"),
(183,"RocketMount_Run"),
(184,"RocketMount_WalkBackwards"),
(185,"RocketMount_SwimIdle"),
(186,"RocketMount_Swim"),
(187,"RocketMount_SwimLeft"),
(188,"RocketMount_SwimRight"),
(189,"RocketMount_SwimBackwards"),
(190,"RocketMount_RunLeft"),
(191,"RocketMount_RunRight"),
(192,"RocketMount_Fly"),
(193,"RocketMount_JumpStart"),
(194,"RocketMount_JumpEnd"),
(195,"RocketMount_Ascending"),
(196,"RocketMount_Descending"),
(197,"SiegeVehicle_AttackThrown"),
(198,"SiegeVehicle_AttackUnarmed"),
(199,"SiegeVehicle_Idle"),
(200,"SiegeVehicleSlow_Fast"),
(202,"WintergraspDemolisher_NotMoving"),
(203,"WintergraspDemolisher_AttackUnarmed"),
(204,"WintergraspDemolisher_Moving"),
(205,"WintergraspDemolisher_AttackThrown"),
(206,"WintergraspDemolisher_LoadThrown"),
(221,"FlyingMachineMount_SwimIdleVar1"),
(222,"FlyingMachineMount_StandVar1"),
(241,"WintergraspDemolisherdeath"),
(242,"WintergraspDemolisherWound"),
(243,"FlyingMachineCreature_VehicleRun"),
(244,"FlyingMachineCreature_VehicleSGroundDown"),
(245,"FlyingMachineCreature_VehicleSitGroundUp"),
(246,"FlyingMachineCreature_VehicleWalk"),
(247,"FlyingMachineCreature_VehicleWalkBackwards"),
(261,"SiegeVehicleDeath"),
(262,"SiegeVehicleWounds"),
(263,"Wintergrasp_Catapult_Death"),
(264,"Wintergrasp_Catapult_Wound"),
(265,"MotorCycleAttackThrown"),
(266,"MotorCycleJumpEnd"),
(267,"MotorCycleJumpStart"),
(268,"MotorCycleLoadThrown"),
(269,"MotorCycleStand"),
(270,"MotorCycleWalkRun"),
(281,"ND_AllianceGunship_Always"),
(282,"HordeGunShipState"),
(321,"Off_Vehicle"),
(341,"Flame Leviathan Wound"),
(342,"Flame Leviathan Death"),
(343,"Flame Leviathan Idle"),
(344,"Flame Leviathan Attack Unarmed"),
(345,"Flame Leviathan Attack Thrown"),
(346,"Flame Leviathan Walk Run"),
(361,"MimironHeadMount_Run"),
(362,"MimironHeadMount_Walk"),
(363,"MimironHeadMount_JumpStart"),
(364,"MimironHeadMount_JumpEnd"),
(365,"SwimIdle"),
(381,"Orc_Fortress_Elevator01"),
(401,"Orc_Fortress_Elevator01_Decellerate"),
(402,"Orc_Fortress_Elevator01_Accellerate"),
(403,"Vr_elevator_lift_Decellerate"),
(404,"Vr_elevator_lift_Moving"),
(405,"Gate"),
(421,"UlduarRaid_GnomeWing_Transport_InMotion"),
(441,"Org_Arena_Gear_Open"),
(461,"Org_Arena_Pulley_Loop"),
(462,"Org_Arena_Firedoor_Open"),
(463,"Org_Arena_Firedoor_Close"),
(464,"Org_Arena_Firedoor_Opened"),
(481,"Ul_train_turnaround_Open"),
(501,"UL_SigilDoor01_Open"),
(521,"VrykulTransportShip_InMotion"),
(541,"hf_elevator_lift_Loop"),
(581,"HordeGunship_00"),
(582,"ND_AllianceGunship_Always_0"),
(601,"IceCrown_Elevator02_Start"),
(602,"IceCrown_Elevator02_ShipMoving"),
(603,"IceCrown_Elevator02_Stop"),
(608,"DeepRunTram_Loop"),
(609,"FlyingCarpetMount_Test"),
(610,"Flying Carpet - Magic Loop"),
(611,"Flying Carpet - Periodic"); 
