DROP TABLE IF EXISTS `ObjectEffectPackage`; 
CREATE TABLE `ObjectEffectPackage` ( `ID` INT NOT NULL DEFAULT '0', `Name` TEXT NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `ObjectEffectPackage` VALUES (12,"vr_elevator_lift"),
(61,"Flying Machine Mount"),
(81,"Wintergrasp Catapult"),
(101,"Rocket Mount"),
(102,"SiegeVehicle"),
(122,"Wintergrasp Demolisher"),
(141,"FlyingMachineCreature_Vehicle"),
(161,"MotorCycle"),
(181,"ND_AllianceGunship"),
(182,"HordeGunShip"),
(201,"TeleportTestPackage"),
(221,"Flame Leviathan (Siege Tank)"),
(241,"MimironHeadMount"),
(261,"Orc_Fortress_Elevator01"),
(281,"vr_elevator_gate"),
(301,"UlduarRaid_GnomeWing_TransportWMO"),
(321,"Org_Arena_Gear"),
(341,"Org_Arena_Pulley"),
(342,"OrgrimmarArena_FireFX"),
(361,"UL_train_turnaround"),
(381,"UL_SigilDoor01"),
(401,"Vrykul_Transport_Ship"),
(421,"hf_elevator_lift"),
(461,"ND_AllianceGunship (Ice Crown)"),
(462,"HordeGunShip (IceCrown)"),
(481,"HordeGunShip (Small)"),
(482,"IceCrown_Elevator02"),
(488,"DeepRunTram"),
(491,"FlyingCarpetMount"); 
