DROP TABLE IF EXISTS `ObjectEffectPackage`; 
CREATE TABLE `ObjectEffectPackage` ( `ID` INT NOT NULL DEFAULT '0', `Name` TEXT NULL, PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `ObjectEffectPackage` VALUES (12,"vr_elevator_lift"); 
INSERT INTO `ObjectEffectPackage` VALUES (61,"Flying Machine Mount"); 
INSERT INTO `ObjectEffectPackage` VALUES (81,"Wintergrasp Catapult"); 
INSERT INTO `ObjectEffectPackage` VALUES (101,"Rocket Mount"); 
INSERT INTO `ObjectEffectPackage` VALUES (102,"SiegeVehicle"); 
INSERT INTO `ObjectEffectPackage` VALUES (122,"Wintergrasp Demolisher"); 
INSERT INTO `ObjectEffectPackage` VALUES (141,"FlyingMachineCreature_Vehicle"); 
INSERT INTO `ObjectEffectPackage` VALUES (161,"MotorCycle"); 
INSERT INTO `ObjectEffectPackage` VALUES (181,"ND_AllianceGunship"); 
INSERT INTO `ObjectEffectPackage` VALUES (182,"HordeGunShip"); 
INSERT INTO `ObjectEffectPackage` VALUES (201,"TeleportTestPackage"); 
INSERT INTO `ObjectEffectPackage` VALUES (221,"Flame Leviathan (Siege Tank)"); 
INSERT INTO `ObjectEffectPackage` VALUES (241,"MimironHeadMount"); 
INSERT INTO `ObjectEffectPackage` VALUES (261,"Orc_Fortress_Elevator01"); 
INSERT INTO `ObjectEffectPackage` VALUES (281,"vr_elevator_gate"); 
INSERT INTO `ObjectEffectPackage` VALUES (301,"UlduarRaid_GnomeWing_TransportWMO"); 
INSERT INTO `ObjectEffectPackage` VALUES (321,"Org_Arena_Gear"); 
INSERT INTO `ObjectEffectPackage` VALUES (341,"Org_Arena_Pulley"); 
INSERT INTO `ObjectEffectPackage` VALUES (342,"OrgrimmarArena_FireFX"); 
INSERT INTO `ObjectEffectPackage` VALUES (361,"UL_train_turnaround"); 
INSERT INTO `ObjectEffectPackage` VALUES (381,"UL_SigilDoor01"); 
INSERT INTO `ObjectEffectPackage` VALUES (401,"Vrykul_Transport_Ship"); 
INSERT INTO `ObjectEffectPackage` VALUES (421,"hf_elevator_lift"); 
INSERT INTO `ObjectEffectPackage` VALUES (461,"ND_AllianceGunship (Ice Crown)"); 
INSERT INTO `ObjectEffectPackage` VALUES (462,"HordeGunShip (IceCrown)"); 
INSERT INTO `ObjectEffectPackage` VALUES (481,"HordeGunShip (Small)"); 
INSERT INTO `ObjectEffectPackage` VALUES (482,"IceCrown_Elevator02"); 
INSERT INTO `ObjectEffectPackage` VALUES (488,"DeepRunTram"); 
INSERT INTO `ObjectEffectPackage` VALUES (491,"FlyingCarpetMount"); 
