DROP TABLE IF EXISTS `PaperDollItemFrame`; 
CREATE TABLE `PaperDollItemFrame` ( `ID` INT NOT NULL DEFAULT '0', `ItemButtonName` TEXT NULL, `SlotIcon` TEXT NULL, `SlotNumber` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `PaperDollItemFrame` VALUES (1,"HeadSlot","interface\paperdoll\UI-PaperDoll-Slot-Head.blp",1),
(2,"NeckSlot","interface\paperdoll\UI-PaperDoll-Slot-Neck.blp",2),
(3,"ShoulderSlot","interface\paperdoll\UI-PaperDoll-Slot-Shoulder.blp",3),
(4,"ShirtSlot","interface\paperdoll\UI-PaperDoll-Slot-Shirt.blp",4),
(5,"ChestSlot","interface\paperdoll\UI-PaperDoll-Slot-Chest.blp",5),
(6,"WaistSlot","interface\paperdoll\UI-PaperDoll-Slot-Waist.blp",6),
(7,"LegsSlot","interface\paperdoll\UI-PaperDoll-Slot-Legs.blp",7),
(8,"FeetSlot","interface\paperdoll\UI-PaperDoll-Slot-Feet.blp",8),
(9,"WristSlot","interface\paperdoll\UI-PaperDoll-Slot-Wrists.blp",9),
(10,"HandsSlot","interface\paperdoll\UI-PaperDoll-Slot-Hands.blp",10),
(11,"Finger0Slot","interface\paperdoll\UI-PaperDoll-Slot-Finger.blp",11),
(12,"Finger1Slot","interface\paperdoll\UI-PaperDoll-Slot-Finger.blp",12),
(13,"Trinket0Slot","interface\paperdoll\UI-PaperDoll-Slot-Trinket.blp",13),
(14,"Trinket1Slot","interface\paperdoll\UI-PaperDoll-Slot-Trinket.blp",14),
(15,"BackSlot","interface\paperdoll\UI-PaperDoll-Slot-Chest.blp",15),
(16,"MainHandSlot","interface\paperdoll\UI-PaperDoll-Slot-MainHand.blp",16),
(17,"SecondaryHandSlot","interface\paperdoll\UI-PaperDoll-Slot-SecondaryHand.blp",17),
(18,"RangedSlot","interface\paperdoll\UI-PaperDoll-Slot-Ranged.blp",18),
(19,"TabardSlot","interface\paperdoll\UI-PaperDoll-Slot-Tabard.blp",19),
(20,"Bag1","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",64),
(21,"Bag2","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",65),
(22,"Bag3","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",66),
(23,"Bag4","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",67),
(24,"Bag5","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",68),
(25,"Bag6","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",69),
(26,"Bag7","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",70),
(27,"Bag8","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",71),
(28,"Bag9","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",72),
(29,"Bag10","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",73),
(30,"Bag11","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",74),
(31,"Bag12","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",75),
(32,"Bag0Slot","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",20),
(33,"Bag1Slot","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",21),
(34,"Bag2Slot","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",22),
(35,"Bag3Slot","interface\paperdoll\UI-PaperDoll-Slot-Bag.blp",23),
(36,"AmmoSlot","interface\paperdoll\UI-PaperDoll-Slot-Ranged.blp",0); 
