DROP TABLE IF EXISTS `Stationery`; 
CREATE TABLE `Stationery` ( `ID` INT NOT NULL DEFAULT '0', `ItemID` INT NOT NULL DEFAULT '0', `Texture` TEXT NULL, `Flags` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `Stationery` VALUES (1,8164,"STATIONERYTEST",0); 
INSERT INTO `Stationery` VALUES (41,9311,"STATIONERYTEST",1); 
INSERT INTO `Stationery` VALUES (61,18154,"GMSTATIONERY",2); 
INSERT INTO `Stationery` VALUES (62,21140,"AUCTIONSTATIONERY",0); 
INSERT INTO `Stationery` VALUES (64,22058,"STATIONERY_VAL",0); 
INSERT INTO `Stationery` VALUES (65,34171,"STATIONERY_CHR",0); 
INSERT INTO `Stationery` VALUES (67,46830,"Stationery_Orp",0); 
