ALTER TABLE achievement
MODIFY Instance_Id INT NULL,
MODIFY Supercedes INT NULL,
MODIFY Category INT NULL,
MODIFY IconID INT NULL,
MODIFY Shares_Criteria INT NULL;

ALTER TABLE achievement_category
MODIFY Parent INT NULL;

ALTER TABLE achievement_criteria
MODIFY Achievement_Id INT NULL;

ALTER TABLE areagroup
MODIFY AreaID_1 INT NULL,
MODIFY AreaID_2 INT NULL,
MODIFY AreaID_3 INT NULL,
MODIFY AreaID_4 INT NULL,
MODIFY AreaID_5 INT NULL,
MODIFY AreaID_6 INT NULL,
MODIFY NextAreaID INT NULL;

ALTER TABLE areapoi
MODIFY FactionID INT NULL,
MODIFY AreaID INT NULL;

ALTER TABLE areatable
MODIFY ContinentID INT NULL,
MODIFY ParentAreaID INT NULL,
MODIFY SoundProviderPref INT NULL,
MODIFY SoundProviderPrefUnderwater INT NULL,
MODIFY AmbienceID INT NULL,
MODIFY ZoneMusic INT NULL,
MODIFY IntroSound INT NULL,
MODIFY LiquidTypeID_1 INT NULL,
MODIFY LiquidTypeID_2 INT NULL,
MODIFY LiquidTypeID_3 INT NULL,
MODIFY LiquidTypeID_4 INT NULL,
MODIFY Lightid INT NULL;

ALTER TABLE areatrigger
MODIFY ContinentID INT NULL;

ALTER TABLE attackanimkits
MODIFY Animation INT NULL,
MODIFY Type INT NULL;

ALTER TABLE auctionhouse
MODIFY FactionID INT NULL;

ALTER TABLE battlemasterlist
MODIFY MapID_1 INT NULL,
MODIFY MapID_2 INT NULL,
MODIFY MapID_3 INT NULL,
MODIFY MapID_4 INT NULL,
MODIFY MapID_5 INT NULL,
MODIFY MapID_6 INT NULL,
MODIFY MapID_7 INT NULL,
MODIFY MapID_8 INT NULL;

ALTER TABLE charbaseinfo
MODIFY RaceID INT NULL,
MODIFY ClassID INT NULL;

ALTER TABLE charhairgeosets
MODIFY RaceID INT NULL;

ALTER TABLE charhairtextures
MODIFY Race INT NULL;

ALTER TABLE charsections
MODIFY RaceID INT NULL;

ALTER TABLE charstartoutfit
MODIFY RaceID INT NULL,
MODIFY ClassID INT NULL;

ALTER TABLE chatchannels
MODIFY FactionGroup INT NULL;

ALTER TABLE chrclasses
MODIFY CinematicSequenceID INT NULL;

ALTER TABLE chrraces
MODIFY FactionID INT NULL,
MODIFY ExplorationSoundID INT NULL,
MODIFY MaleDisplayId INT NULL,
MODIFY FemaleDisplayId INT NULL,
MODIFY CreatureType INT NULL,
MODIFY CinematicSequenceID INT NULL;

ALTER TABLE cinematiccamera
MODIFY SoundID INT NULL;

ALTER TABLE cinematicsequences
MODIFY SoundID INT NULL,
MODIFY Camera_1 INT NULL,
MODIFY Camera_2 INT NULL,
MODIFY Camera_3 INT NULL,
MODIFY Camera_4 INT NULL,
MODIFY Camera_5 INT NULL,
MODIFY Camera_6 INT NULL,
MODIFY Camera_7 INT NULL,
MODIFY Camera_8 INT NULL;

ALTER TABLE creaturedisplayinfo
MODIFY ModelID INT NULL,
MODIFY SoundID INT NULL,
MODIFY ExtendedDisplayInfoID INT NULL,
MODIFY BloodLevel INT NULL,
MODIFY BloodID INT NULL,
MODIFY NPCSoundID INT NULL,
MODIFY ParticleColorID INT NULL,
MODIFY ObjectEffectPackageID INT NULL;

ALTER TABLE creaturedisplayinfoextra
MODIFY DisplayRaceID INT NULL,
MODIFY NPCItemDisplay_1 INT NULL,
MODIFY NPCItemDisplay_2 INT NULL,
MODIFY NPCItemDisplay_3 INT NULL,
MODIFY NPCItemDisplay_4 INT NULL,
MODIFY NPCItemDisplay_5 INT NULL,
MODIFY NPCItemDisplay_6 INT NULL,
MODIFY NPCItemDisplay_7 INT NULL,
MODIFY NPCItemDisplay_8 INT NULL,
MODIFY NPCItemDisplay_9 INT NULL,
MODIFY NPCItemDisplay_10 INT NULL,
MODIFY NPCItemDisplay_11 INT NULL;

ALTER TABLE creaturefamily
MODIFY SkillLine_1 INT NULL,
MODIFY SkillLine_2 INT NULL;

ALTER TABLE creaturemodeldata
MODIFY BloodID INT NULL,
MODIFY FootprintTextureID INT NULL,
MODIFY FootstepShakeSize INT NULL,
MODIFY DeathThudShakeSize INT NULL,
MODIFY SoundID INT NULL;

ALTER TABLE creaturesounddata
MODIFY SoundExertionID INT NULL,
MODIFY SoundExertionCriticalID INT NULL,
MODIFY SoundInjuryID INT NULL,
MODIFY SoundInjuryCriticalID INT NULL,
MODIFY SoundInjuryCrushingBlowID INT NULL,
MODIFY SoundDeathID INT NULL,
MODIFY SoundStunID INT NULL,
MODIFY SoundStandID INT NULL,
MODIFY SoundFootstepID INT NULL,
MODIFY SoundAggroID INT NULL,
MODIFY SoundWingFlapID INT NULL,
MODIFY SoundWingGlideID INT NULL,
MODIFY SoundAlertID INT NULL,
MODIFY SoundFidget_1 INT NULL,
MODIFY SoundFidget_2 INT NULL,
MODIFY SoundFidget_3 INT NULL,
MODIFY SoundFidget_4 INT NULL,
MODIFY SoundFidget_5 INT NULL,
MODIFY NPCSoundID INT NULL,
MODIFY LoopSoundID INT NULL,
MODIFY SoundJumpStartID INT NULL,
MODIFY SoundJumpEndID INT NULL,
MODIFY SoundPetAttackID INT NULL,
MODIFY SoundPetOrderID INT NULL,
MODIFY SoundPetDismissID INT NULL,
MODIFY BirthSoundID INT NULL,
MODIFY SpellCastDirectedSoundID INT NULL,
MODIFY SubmergeSoundID INT NULL,
MODIFY SubmergedSoundID INT NULL;

ALTER TABLE creaturespelldata
MODIFY Spells_1 INT NULL,
MODIFY Spells_2 INT NULL,
MODIFY Spells_3 INT NULL,
MODIFY Spells_4 INT NULL;

ALTER TABLE deaththudlookups
MODIFY TerraintypeSoundID INT NULL,
MODIFY SoundEntryID INT NULL,
MODIFY SoundEntryIDWater INT NULL;

ALTER TABLE declinedwordcases
MODIFY DeclinedWordID INT NULL;

ALTER TABLE dungeonencounter
MODIFY MapID INT NULL,
MODIFY Difficulty INT NULL;

ALTER TABLE dungeonmap
MODIFY MapID INT NULL,
MODIFY ParentWorldMapID INT NULL;

ALTER TABLE dungeonmapchunk
MODIFY MapID INT NULL,
MODIFY WmoGroupID INT NULL,
MODIFY DungeonMapID INT NULL;

ALTER TABLE emotes
MODIFY AnimID INT NULL,
MODIFY EventSoundID INT NULL;

ALTER TABLE emotestext
MODIFY EmoteID INT NULL,
MODIFY EmoteText_1 INT NULL,
MODIFY EmoteText_2 INT NULL,
MODIFY EmoteText_3 INT NULL,
MODIFY EmoteText_4 INT NULL,
MODIFY EmoteText_5 INT NULL,
MODIFY EmoteText_6 INT NULL,
MODIFY EmoteText_7 INT NULL,
MODIFY EmoteText_8 INT NULL,
MODIFY EmoteText_9 INT NULL,
MODIFY EmoteText_10 INT NULL,
MODIFY EmoteText_11 INT NULL,
MODIFY EmoteText_12 INT NULL,
MODIFY EmoteText_13 INT NULL,
MODIFY EmoteText_14 INT NULL,
MODIFY EmoteText_15 INT NULL,
MODIFY EmoteText_16 INT NULL;

ALTER TABLE emotestextsound
MODIFY EmotesTextID INT NULL,
MODIFY RaceID INT NULL,
MODIFY SoundID INT NULL;

ALTER TABLE environmentaldamage
MODIFY VisualkitID INT NULL;

ALTER TABLE faction
MODIFY ParentFactionID INT NULL;

ALTER TABLE faction
MODIFY ParentFactionID INT NULL;

ALTER TABLE factiontemplate
MODIFY Faction INT NULL,
MODIFY Enemies_1 INT NULL,
MODIFY Enemies_2 INT NULL,
MODIFY Enemies_3 INT NULL,
MODIFY Enemies_4 INT NULL,
MODIFY Friend_1 INT NULL,
MODIFY Friend_2 INT NULL,
MODIFY Friend_3 INT NULL,
MODIFY Friend_4 INT NULL;

ALTER TABLE footstepterrainlookup
MODIFY CreatureFootstepID INT NULL,
MODIFY TerrainSoundID INT NULL,
MODIFY SoundID INT NULL,
MODIFY SoundIDSplash INT NULL;

ALTER TABLE gameobjectdisplayinfo
MODIFY Sound_1 INT NULL,
MODIFY Sound_2 INT NULL,
MODIFY Sound_3 INT NULL,
MODIFY Sound_4 INT NULL,
MODIFY Sound_5 INT NULL,
MODIFY Sound_6 INT NULL,
MODIFY Sound_7 INT NULL,
MODIFY Sound_8 INT NULL,
MODIFY Sound_9 INT NULL,
MODIFY Sound_10 INT NULL,
MODIFY ObjectEffectPackageID INT NULL;

ALTER TABLE gemproperties
MODIFY Enchant_Id INT NULL;

ALTER TABLE glyphproperties
MODIFY SpellID INT NULL,
MODIFY SpellIconID INT NULL;

ALTER TABLE gmsurveyanswers
MODIFY GMSurveyQuestionID INT NULL;

ALTER TABLE gmsurveycurrentsurvey
MODIFY GMSURVEY_ID INT NULL;

ALTER TABLE gmsurveysurveys
MODIFY Q_1 INT NULL,
MODIFY Q_2 INT NULL,
MODIFY Q_3 INT NULL,
MODIFY Q_4 INT NULL,
MODIFY Q_5 INT NULL,
MODIFY Q_6 INT NULL,
MODIFY Q_7 INT NULL,
MODIFY Q_8 INT NULL,
MODIFY Q_9 INT NULL,
MODIFY Q_10 INT NULL;

ALTER TABLE groundeffecttexture
MODIFY DoodadId_1 INT NULL,
MODIFY DoodadId_2 INT NULL,
MODIFY DoodadId_3 INT NULL,
MODIFY DoodadId_4 INT NULL;

ALTER TABLE holidays
MODIFY HolidayNameID INT NULL,
MODIFY HolidayDescriptionID INT NULL;

ALTER TABLE item
MODIFY ClassID INT NULL,
MODIFY SubclassID INT NULL,
MODIFY Material INT NULL,
MODIFY DisplayInfoID INT NULL;

ALTER TABLE itemdisplayinfo
MODIFY GroupSoundIndex INT NULL,
MODIFY HelmetGeosetVis_1 INT NULL,
MODIFY HelmetGeosetVis_2 INT NULL,
MODIFY ItemVisual INT NULL;

ALTER TABLE itemextendedcost
MODIFY ItemPurchaseGroup INT NULL;

ALTER TABLE itemgroupsounds
MODIFY Sound_1 INT NULL,
MODIFY Sound_2 INT NULL,
MODIFY Sound_3 INT NULL,
MODIFY Sound_4 INT NULL;

ALTER TABLE itempurchasegroup
MODIFY ItemID_1 INT NULL,
MODIFY ItemID_2 INT NULL,
MODIFY ItemID_3 INT NULL,
MODIFY ItemID_4 INT NULL,
MODIFY ItemID_5 INT NULL,
MODIFY ItemID_6 INT NULL,
MODIFY ItemID_7 INT NULL,
MODIFY ItemID_8 INT NULL;

ALTER TABLE itemrandomproperties
MODIFY Enchantment_1 INT NULL,
MODIFY Enchantment_2 INT NULL,
MODIFY Enchantment_3 INT NULL,
MODIFY Enchantment_4 INT NULL,
MODIFY Enchantment_5 INT NULL;

ALTER TABLE itemrandomsuffix
MODIFY Enchantment_1 INT NULL,
MODIFY Enchantment_2 INT NULL,
MODIFY Enchantment_3 INT NULL,
MODIFY Enchantment_4 INT NULL,
MODIFY Enchantment_5 INT NULL;

ALTER TABLE itemset
MODIFY ItemID_1 INT NULL,
MODIFY ItemID_2 INT NULL,
MODIFY ItemID_3 INT NULL,
MODIFY ItemID_4 INT NULL,
MODIFY ItemID_5 INT NULL,
MODIFY ItemID_6 INT NULL,
MODIFY ItemID_7 INT NULL,
MODIFY ItemID_8 INT NULL,
MODIFY ItemID_9 INT NULL,
MODIFY ItemID_10 INT NULL,
MODIFY ItemID_11 INT NULL,
MODIFY ItemID_12 INT NULL,
MODIFY ItemID_13 INT NULL,
MODIFY ItemID_14 INT NULL,
MODIFY ItemID_15 INT NULL,
MODIFY ItemID_16 INT NULL,
MODIFY ItemID_17 INT NULL,
MODIFY SetSpellID_1 INT NULL,
MODIFY SetSpellID_2 INT NULL,
MODIFY SetSpellID_3 INT NULL,
MODIFY SetSpellID_4 INT NULL,
MODIFY SetSpellID_5 INT NULL,
MODIFY SetSpellID_6 INT NULL,
MODIFY SetSpellID_7 INT NULL,
MODIFY SetSpellID_8 INT NULL,
MODIFY RequiredSkill INT NULL;

ALTER TABLE itemsubclass
MODIFY ClassID INT NULL;

ALTER TABLE itemvisuals
MODIFY Slot_1 INT NULL,
MODIFY Slot_2 INT NULL,
MODIFY Slot_3 INT NULL,
MODIFY Slot_4 INT NULL,
MODIFY Slot_5 INT NULL;

ALTER TABLE languagewords
MODIFY LanguageID INT NULL;

ALTER TABLE lfgdungeonexpansion
MODIFY Lfg_Id INT NULL;

ALTER TABLE lfgdungeons
MODIFY MapID INT NULL,
MODIFY Faction INT NULL;

ALTER TABLE lightparams
MODIFY LightSkyboxID INT NULL;

ALTER TABLE loadingscreentaxisplines
MODIFY PathID INT NULL;

ALTER TABLE `lock`
MODIFY Type_1 INT NULL,
MODIFY Type_2 INT NULL,
MODIFY Type_3 INT NULL,
MODIFY Type_4 INT NULL,
MODIFY Type_5 INT NULL,
MODIFY Type_6 INT NULL,
MODIFY Type_7 INT NULL,
MODIFY Type_8 INT NULL;

ALTER TABLE map
MODIFY AreaTableID INT NULL,
MODIFY LoadingScreenID INT NULL,
MODIFY CorpseMapID INT NULL;

ALTER TABLE mapdifficulty
MODIFY MapID INT NULL;

ALTER TABLE material
MODIFY FoleySoundID INT NULL,
MODIFY SheatheSoundID INT NULL,
MODIFY UnsheatheSoundID INT NULL;

ALTER TABLE namegen
MODIFY RaceID INT NULL;

ALTER TABLE npcsounds
MODIFY SoundID_1 INT NULL,
MODIFY SoundID_2 INT NULL,
MODIFY SoundID_3 INT NULL,
MODIFY SoundID_4 INT NULL;

ALTER TABLE objecteffect
MODIFY ObjectEffectGroupID INT NULL,
MODIFY ObjectEffectModifierID INT NULL;

ALTER TABLE objecteffectpackageelem
MODIFY ObjectEffectGroupID INT NULL,
MODIFY ObjectEffectPackageID INT NULL;

ALTER TABLE overridespelldata
MODIFY Spells_1 INT NULL,
MODIFY Spells_2 INT NULL,
MODIFY Spells_3 INT NULL,
MODIFY Spells_4 INT NULL,
MODIFY Spells_5 INT NULL,
MODIFY Spells_6 INT NULL,
MODIFY Spells_7 INT NULL,
MODIFY Spells_8 INT NULL,
MODIFY Spells_9 INT NULL,
MODIFY Spells_10 INT NULL;

ALTER TABLE pvpdifficulty
MODIFY MapID INT NULL;

ALTER TABLE sheathesoundlookups
MODIFY ItemClass INT NULL,
MODIFY ItemSubclass INT NULL,
MODIFY SheathSoundID INT NULL,
MODIFY UnsheathSoundID INT NULL;

ALTER TABLE skillline
MODIFY CategoryID INT NULL,
MODIFY SkillCostsID INT NULL,
MODIFY SpellIconID INT NULL;

ALTER TABLE skilllineability
MODIFY SkillLine INT NULL,
MODIFY Spell INT NULL;

ALTER TABLE skillraceclassinfo
MODIFY SkillID INT NULL,
MODIFY SkillTierID INT NULL,
MODIFY SkillCostIndex INT NULL;

ALTER TABLE soundambience
MODIFY AmbienceID_1 INT NULL,
MODIFY AmbienceID_2 INT NULL;

ALTER TABLE soundemitters
MODIFY SoundEntriesID INT NULL,
MODIFY MapID INT NULL;

ALTER TABLE soundentries
MODIFY SoundEntriesAdvancedID INT NULL;

ALTER TABLE soundentriesadvanced
MODIFY SoundEntryID INT NULL;

ALTER TABLE soundwatertype
MODIFY SoundID INT NULL;

UPDATE spell SET SpellDescriptionVariableID = 0 WHERE SpellDescriptionVariableID = 4294967295;
ALTER TABLE spell
MODIFY Category INT NULL,
MODIFY DispelType INT NULL,
MODIFY Mechanic INT NULL,
MODIFY RequiresSpellFocus INT NULL,
MODIFY CastingTimeIndex INT NULL,
MODIFY DurationIndex INT NULL,
MODIFY RangeIndex INT NULL,
MODIFY EffectMechanic_1 INT NULL,
MODIFY EffectMechanic_2 INT NULL,
MODIFY EffectMechanic_3 INT NULL,
MODIFY EffectRadiusIndex_1 INT NULL,
MODIFY EffectRadiusIndex_2 INT NULL,
MODIFY EffectRadiusIndex_3 INT NULL,
MODIFY RequiredTotemCategoryID_1 INT NULL,
MODIFY RequiredTotemCategoryID_2 INT NULL,
MODIFY Reagent_1 INT NULL,
MODIFY Reagent_2 INT NULL,
MODIFY Reagent_3 INT NULL,
MODIFY Reagent_4 INT NULL,
MODIFY Reagent_5 INT NULL,
MODIFY Reagent_6 INT NULL,
MODIFY Reagent_7 INT NULL,
MODIFY Reagent_8 INT NULL,
MODIFY SpellVisualID_1 INT NULL,
MODIFY SpellVisualID_2 INT NULL,
MODIFY SpellIconID INT NULL,
MODIFY ActiveIconID INT NULL,
MODIFY RequiredAreasID INT NULL,
MODIFY RuneCostID INT NULL,
MODIFY SpellMissileID INT NULL,
MODIFY SpellDescriptionVariableID INT NULL,
MODIFY SpellDifficultyID INT NULL,
MODIFY PowerDisplayID INT NULL;

ALTER TABLE spelldifficulty
MODIFY DifficultySpellID_1 INT NULL,
MODIFY DifficultySpellID_2 INT NULL,
MODIFY DifficultySpellID_3 INT NULL,
MODIFY DifficultySpellID_4 INT NULL;

ALTER TABLE spelleffectcamerashakes
MODIFY CameraShake_1 INT NULL,
MODIFY CameraShake_2 INT NULL,
MODIFY CameraShake_3 INT NULL;

ALTER TABLE spellitemenchantment
MODIFY Effect_1 INT NULL,
MODIFY Effect_2 INT NULL,
MODIFY Effect_3 INT NULL,
MODIFY ItemVisual INT NULL,
MODIFY Src_ItemID INT NULL,
MODIFY Condition_Id INT NULL,
MODIFY RequiredSkillID INT NULL;

ALTER TABLE spellshapeshiftform
MODIFY CreatureType INT NULL,
MODIFY AttackIconID INT NULL,
MODIFY CreatureDisplayID_1 INT NULL,
MODIFY CreatureDisplayID_2 INT NULL,
MODIFY CreatureDisplayID_3 INT NULL,
MODIFY CreatureDisplayID_4 INT NULL,
MODIFY PresetSpellID_1 INT NULL,
MODIFY PresetSpellID_2 INT NULL,
MODIFY PresetSpellID_3 INT NULL,
MODIFY PresetSpellID_4 INT NULL,
MODIFY PresetSpellID_5 INT NULL,
MODIFY PresetSpellID_6 INT NULL,
MODIFY PresetSpellID_7 INT NULL,
MODIFY PresetSpellID_8 INT NULL;

ALTER TABLE spellvisual
MODIFY PrecastKit INT NULL,
MODIFY CastKit INT NULL,
MODIFY ImpactKit INT NULL,
MODIFY StateKit INT NULL,
MODIFY StateDoneKit INT NULL,
MODIFY ChannelKit INT NULL,
MODIFY MissileModel INT NULL,
MODIFY MissileSound INT NULL,
MODIFY AnimEventSoundID INT NULL,
MODIFY CasterImpactKit INT NULL,
MODIFY TargetImpactKit INT NULL,
MODIFY MissileTargetingKit INT NULL,
MODIFY InstantAreaKit INT NULL,
MODIFY ImpactAreaKit INT NULL,
MODIFY PersistentAreaKit INT NULL;

ALTER TABLE spellvisualkit
MODIFY StartAnimID INT NULL,
MODIFY AnimID INT NULL,
MODIFY HeadEffect INT NULL,
MODIFY ChestEffect INT NULL,
MODIFY BaseEffect INT NULL,
MODIFY LeftHandEffect INT NULL,
MODIFY RightHandEffect INT NULL,
MODIFY BreathEffect INT NULL,
MODIFY LeftWeaponEffect INT NULL,
MODIFY RightWeaponEffect INT NULL,
MODIFY SpecialEffect_1 INT NULL,
MODIFY SpecialEffect_2 INT NULL,
MODIFY SpecialEffect_3 INT NULL,
MODIFY WorldEffect INT NULL,
MODIFY SoundID INT NULL,
MODIFY ShakeID INT NULL;

ALTER TABLE spellvisualkitmodelattach
MODIFY ParentSpellVisualKitID INT NULL,
MODIFY SpellVisualEffectNameID INT NULL;

ALTER TABLE stationery
MODIFY ItemID INT NULL;

ALTER TABLE talent
MODIFY TabID INT NULL,
MODIFY SpellRank_1 INT NULL,
MODIFY SpellRank_2 INT NULL,
MODIFY SpellRank_3 INT NULL,
MODIFY SpellRank_4 INT NULL,
MODIFY SpellRank_5 INT NULL,
MODIFY SpellRank_6 INT NULL,
MODIFY SpellRank_7 INT NULL,
MODIFY SpellRank_8 INT NULL,
MODIFY SpellRank_9 INT NULL,
MODIFY PrereqTalent_1 INT NULL,
MODIFY PrereqTalent_2 INT NULL,
MODIFY PrereqTalent_3 INT NULL,
MODIFY RequiredSpellID INT NULL;

ALTER TABLE talenttab
MODIFY SpellIconID INT NULL;

ALTER TABLE taxinodes
MODIFY ContinentID INT NULL;

ALTER TABLE taxipath
MODIFY FromTaxiNode INT NULL,
MODIFY ToTaxiNode INT NULL;

ALTER TABLE taxipathnode
MODIFY PathID INT NULL,
MODIFY ContinentID INT NULL;

ALTER TABLE terraintype
MODIFY FootstepSprayRun INT NULL,
MODIFY FootstepSprayWalk INT NULL,
MODIFY SoundID INT NULL;

ALTER TABLE transportanimation
MODIFY SequenceID INT NULL;

ALTER TABLE uisoundlookups
MODIFY SoundID INT NULL;

ALTER TABLE vehicle
MODIFY PowerDisplayID_1 INT NULL,
MODIFY PowerDisplayID_2 INT NULL,
MODIFY PowerDisplayID_3 INT NULL;

ALTER TABLE vehicleuiindseat
MODIFY VehicleUIIndicatorID INT NULL;

ALTER TABLE vocaluisounds
MODIFY RaceID INT NULL,
MODIFY NormalSoundID_1 INT NULL,
MODIFY NormalSoundID_2 INT NULL,
MODIFY PissedSoundID_1 INT NULL,
MODIFY PissedSoundID_2 INT NULL;

ALTER TABLE weaponimpactsounds
MODIFY ImpactSoundID_1 INT NULL,
MODIFY ImpactSoundID_2 INT NULL,
MODIFY ImpactSoundID_3 INT NULL,
MODIFY ImpactSoundID_4 INT NULL,
MODIFY ImpactSoundID_5 INT NULL,
MODIFY ImpactSoundID_6 INT NULL,
MODIFY ImpactSoundID_7 INT NULL,
MODIFY ImpactSoundID_8 INT NULL,
MODIFY ImpactSoundID_9 INT NULL,
MODIFY ImpactSoundID_10 INT NULL,
MODIFY CritImpactSoundID_1 INT NULL,
MODIFY CritImpactSoundID_2 INT NULL,
MODIFY CritImpactSoundID_3 INT NULL,
MODIFY CritImpactSoundID_4 INT NULL,
MODIFY CritImpactSoundID_5 INT NULL,
MODIFY CritImpactSoundID_6 INT NULL,
MODIFY CritImpactSoundID_7 INT NULL,
MODIFY CritImpactSoundID_8 INT NULL,
MODIFY CritImpactSoundID_9 INT NULL,
MODIFY CritImpactSoundID_10 INT NULL;

ALTER TABLE weaponswingsounds2
MODIFY SoundID INT NULL;

ALTER TABLE weather
MODIFY AmbienceID INT NULL;

ALTER TABLE wmoareatable
MODIFY SoundProviderPref INT NULL,
MODIFY SoundProviderPrefUnderwater INT NULL,
MODIFY AmbienceID INT NULL,
MODIFY ZoneMusic INT NULL,
MODIFY AreaTableID INT NULL,
MODIFY IntroSound INT NULL;

ALTER TABLE worldmaparea
MODIFY MapID INT NULL,
MODIFY AreaID INT NULL,
MODIFY DisplayMapID INT NULL,
MODIFY DefaultDungeonFloor INT NULL,
MODIFY ParentWorldMapID INT NULL;

ALTER TABLE worldmapcontinent
MODIFY MapID INT NULL;

ALTER TABLE worldmapoverlay
MODIFY MapAreaID INT NULL,
MODIFY AreaID_1 INT NULL,
MODIFY AreaID_2 INT NULL,
MODIFY AreaID_3 INT NULL,
MODIFY AreaID_4 INT NULL;

ALTER TABLE worldmaptransforms
MODIFY MapID INT NULL,
MODIFY NewMapID INT NULL,
MODIFY NewDungeonMapID INT NULL;

ALTER TABLE worldsafelocs
MODIFY Continent INT NULL;

ALTER TABLE worldstateui
MODIFY MapID INT NULL,
MODIFY AreaID INT NULL;

ALTER TABLE worldstatezonesounds
MODIFY AreaID INT NULL,
MODIFY WMOAreaID INT NULL,
MODIFY ZoneintroMusicID INT NULL,
MODIFY ZoneMusicID INT NULL,
MODIFY SoundAmbienceID INT NULL,
MODIFY SoundProviderPreferencesID INT NULL;

ALTER TABLE zoneintromusictable
MODIFY SoundID INT NULL;

ALTER TABLE zonemusic
MODIFY Sounds_1 INT NULL,
MODIFY Sounds_2 INT NULL;

