DROP TABLE IF EXISTS `HolidayNames`; 
CREATE TABLE `HolidayNames` ( `ID` INT NOT NULL DEFAULT '0', `Name_Lang_enUS` TEXT NULL, `Name_Lang_enGB` TEXT NULL, `Name_Lang_koKR` TEXT NULL, `Name_Lang_frFR` TEXT NULL, `Name_Lang_deDE` TEXT NULL, `Name_Lang_enCN` TEXT NULL, `Name_Lang_zhCN` TEXT NULL, `Name_Lang_enTW` TEXT NULL, `Name_Lang_zhTW` TEXT NULL, `Name_Lang_esES` TEXT NULL, `Name_Lang_esMX` TEXT NULL, `Name_Lang_ruRU` TEXT NULL, `Name_Lang_ptPT` TEXT NULL, `Name_Lang_ptBR` TEXT NULL, `Name_Lang_itIT` TEXT NULL, `Name_Lang_Unk` TEXT NULL, `Name_Lang_Mask` INT UNSIGNED NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `HolidayNames` VALUES (1,"Darkmoon Faire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (5,"Fireworks Celebration","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (6,"Stranglethorn Fishing Extravaganza","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (7,"Brewfest","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (9,"Love is in the Air","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (11,"Midsummer Fire Festival","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (12,"Fireworks Spectacular","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (13,"Children's Week","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (14,"Feast of Winter Veil","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (15,"Noblegarden","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (16,"Hallow's End","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (17,"Harvest Festival","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (18,"Lunar Festival","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (19,"Brewfest","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (21,"Pirates' Day","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (22,"Call to Arms: Alterac Valley","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (23,"Call to Arms: Arathi Basin","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (24,"Call to Arms: Eye of the Storm","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (25,"Call to Arms: Warsong Gulch","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (41,"Call to Arms: Strand of the Ancients","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (61,"Wrath of the Lich King Launch","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (81,"Day of the Dead","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (101,"Pilgrim's Bounty","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (121,"Call to Arms: Isle of Conquest","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (141,"Mohawk Promotion","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `HolidayNames` VALUES (161,"Kalu'ak Fishing Derby","","","","","","","","","","","","","","","",16712190); 
