DROP TABLE IF EXISTS `LiquidMaterial`; 
CREATE TABLE `LiquidMaterial` ( `ID` INT NOT NULL DEFAULT '0', `LVF` INT NOT NULL DEFAULT '0', `Flags` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `LiquidMaterial` VALUES (1,0,1); 
INSERT INTO `LiquidMaterial` VALUES (2,1,0); 
INSERT INTO `LiquidMaterial` VALUES (3,0,1); 
