DROP TABLE IF EXISTS `SpellVisualKitAreaModel`; 
CREATE TABLE `SpellVisualKitAreaModel` ( `ID` INT NOT NULL DEFAULT '0', `Name` TEXT NULL, `EnumID` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `SpellVisualKitAreaModel` VALUES (1,"Spells\Blizzard_Impact_Base.mdx",0); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (2,"Spells\RainOfFire_Impact_Base.mdx",1); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (3,"Spells\CallLightning_Impact.mdx",2); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (4,"Spells\FlamestrikeSmall_Impact_Base.mdx",3); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (5,"Spells\DeathAndDecay_Area_Base.mdx",4); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (6,"Spells\ArcaneShot_Area.mdx",5); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (7,"Spells\StarShards_Impact_Base.mdx",6); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (8,"Spells\Fel_RainOfFire_Impact_Base.mdx",7); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (9,"Spells\HellfireRaid_Dust_Impact_Base.mdx",8); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (21,"Spells\DeathAndDecay.mdx",9); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (41,"Spells\DeathKnight_Desecration.mdx",10); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (61,"Spells\Druid_StarfallMissile.mdx",11); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (81,"Spells\archimonde_fire.mdx",12); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (82,"Spells\Archimonde_Blue_Fire.mdx",13); 
INSERT INTO `SpellVisualKitAreaModel` VALUES (83,"Spells\DeathAndDecayGreen.mdx",14); 
