DROP TABLE IF EXISTS `WeaponSwingSounds2`; 
CREATE TABLE `WeaponSwingSounds2` ( `ID` INT NOT NULL DEFAULT '0', `SwingType` INT NOT NULL DEFAULT '0', `Crit` INT NOT NULL DEFAULT '0', `SoundID` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
INSERT INTO `WeaponSwingSounds2` VALUES (1,0,0,233); 
INSERT INTO `WeaponSwingSounds2` VALUES (2,0,1,234); 
INSERT INTO `WeaponSwingSounds2` VALUES (3,1,0,235); 
INSERT INTO `WeaponSwingSounds2` VALUES (4,1,1,236); 
INSERT INTO `WeaponSwingSounds2` VALUES (5,2,0,237); 
INSERT INTO `WeaponSwingSounds2` VALUES (6,2,1,238); 
